export const ADD_NEW_TASK="ADD_NEW_TASK"
export const ADD_NEW_TASK_REQ="ADD_NEW_TASK_REQ"
export const DELETE_TASK="DELETE_TASK"
export const TOGGLE_TASK_STATUS="TOGGLE_TASK_STATUS"
export const EDIT_TASK="EDIT_TASK"
export const GET_ALL_TASK="GET_ALL_TASK"
export const GET_ALL_TASK_REQ="GET_ALL_TASK_REQ"
export const DELETE_TASK_REQ="DELETE_TASK_REQ"
export const TOGGLE_TASK_STATUS_REQ="TOGGLE_TASK_STATUS_REQ"
export const UPDATE_TASK_STATUS_REQ="UPDATE_TASK_STATUS_REQ"
export const UPDATE_TASK_STATUS="UPDATE_TASK_STATUS"



